spring.application.name=cnn-articles-search
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# Disable DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
